### ISSUE TITLE
Bug (?) Not working with remapped keys

### ISSUE THREAD

**Issue by chrisgrieser** [asiryk/auto-hlsearch.nvim#1]
Thanks for the nice plugin!

So I tried out the plugin and it works fine with the default search commands like `n` or `/`. However, I have mapped `-` to `/`, and also `+` to `*`, and both do not work properly.

- `-` highlights when pressed, but removes the highlights once pressing `<CR>`.
- `+` works fine, after being done with `++++`, it does not remove the highlight

```lua
require("auto-hlsearch").setup {
	remap_keys = { "n", "N" },
}
vim.keymap.set("n", "-", ":AutoHlsearch<CR>/")
vim.keymap.set("n", "+", ":AutoHlsearch<CR>*")
```

both issues occur regardless whether I add `+` and `-` to the `remap_keys` list or not.

**Comment by chrisgrieser** [comment]
ah nevermind, got it working, I needed to include *the original mappings* in the remap table.

**Comment by asiryk** [comment]
Hi @chrisgrieser! Thanks for using the plugin and thank you for the star! Indeed this was a bug. The * and # keys trigger CursorMove autocmd, so the hlsearch has been cleared immediately. I added these to ignore keys. Now your case should work fine.
